# Site settings
title: Aman Nepid
description: 'Break Some Rules ... Make Some Noise'
url: 'amannepid.github.io'
# baseurl: '/jekyll-uno/'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

avatar_path: https://avatars1.githubusercontent.com/u/1026439

author:
  name: 'Dipendra Sunar'
  # email: aman.nepid@gmail.com
  twitter_username: amannepid
  # facebook_username: joshgerdes
  github_username:  amannepid
  linkedin_username:  nepid

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 5
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']

gems:
  - jemoji
exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
